window.TPA_CATALOGO_B = "";
window.TPA_CATALOGO_A = (function () {
  const cards = [
    ["images/productos/levadiza-seccional.jpg","Motor Levadiza","LIFTMASTER USA / BFT ITALIA","#0B1E3D","#fff","Motor para puerta Levadiza y Seccional",["Tenemos motores de las marcas BFT y LIFTMASTER en todos sus modelos y capacidades.","Motores con transmisión de faja y cadena.","Motores electrónicos y con conexión WIFI.","Para uso residencial y alto tránsito."],"Cotizar este Motor","https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600"],
    ["images/productos/corredizo.jpg","Motor Corredizo","LIFTMASTER / BFT","#0B1E3D","#fff","Motor de cremallera para portón corredizo",["Tenemos motores de las marcas BFT y LIFTMASTER en todos sus modelos y capacidades.","Motores para uso residencial.","Motores para uso industrial y alto tránsito.","Repuestos originales y servicio técnico."],"Cotizar este Motor","https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=600"],
    ["images/productos/batiente-hidraulico.jpg","Brazos Hidraulicos","BFT ITALIA","#D9202E","#fff","Brazos HIDRÁULICOS para puerta batiente",["Marca BFT (italiana), reconocida a nivel mundial y líder en su sector.","Para puertas pesadas y alta frecuencia de uso.","Ideal para edificios y urbanizaciones.","Larga vida útil y bajo costo de mantenimiento."],"Cotizar este Motor","https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600"],
    ["images/productos/batiente-electromecanico.jpg","Brazos Electromecanicos","LIFTMASTER / BFT","#0B1E3D","#fff","Brazos ELECTROMECÁNICOS puerta batiente",["Marcas más reconocidas: LIFTMASTER (EE.UU.) y BFT (Italia).","Equipos de alta gama y gran rendimiento.","Ideal para casas o residencias de varios usuarios.","Larga vida útil y bajo costo de mantenimiento."],"Cotizar este Motor","https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600"],
    ["images/productos/jielong.jpg","Motor Jielong","JIELONG INDUSTRIAL","#E5A000","#0B1E3D","Motor Lateral JIELONG para puerta enrollable",["Más de 40 años en Perú, única marca bicertificada.","Motores AC de 220V y DC de 24V con UPS (Batería).","Capacidad de carga desde 400 kg hasta 2000 kg.","Repuestos originales y servicio técnico."],"Cotizar este Motor","https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=600"],
    ["images/productos/beninca-ereka.jpg","Beninca Ereka","BENINCA / ERREKA","#0F7B52","#fff","Motor Central para puerta enrollable",["Ideal para puertas de tiendas y comercios.","Se adapta fácilmente a cualquier puerta enrollable.","Motores AC de 220V con central y control remoto.","Desde 200 kg hasta 300 kg de capacidad. 100% confiable."],"Cotizar Repuestos","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600"],
    ["images/productos/kit-levadiza.jpg","Kit de accesorios","REPUESTOS ORIGINALES","#0B1E3D","#FFB800","KIT de accesorios para puerta levadiza",["Para puertas levadizas de metal o madera.","Resortes de tracción desde 50 hasta 150 kg.","Brazos semipesados, pesados y tipo tijera.","Viga soporte, fundas, pestillos automáticos."],"Cotizar este Motor","https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600"],
    ["images/productos/controles.jpg","Transmisores y receptores","BENINCA / ERREKA","#0F7B52","#fff","Transmisores y receptores de todas las marcas",["Controles y receptores originales para todo accionamiento.","Controles remotos o transmisores de todas las marcas.","Receptores externos adaptables a cualquier motor.","Equipos originales y 100% garantizados."],"Cotizar este Motor","https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600"],
    ["images/productos/repuestos.jpg","Accesorios y Repuestos Multimarca","REPUESTOS ORIGINALES","#0B1E3D","#FFB800","Accesorios y Repuestos Multimarca",["Venta directa de repuestos: controles, fotocélulas, cremalleras y tarjetas.","Controles remotos programados.","Cremalleras de acero y nylon (metro).","Fotocélulas infrarrojas y tarjetas electrónicas."],"Cotizar Repuestos","https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600"]
  ];
  const items = cards.map(function (c) {
    const lis = c[6].map(function (t) {
      return '<li class="flex items-start gap-2"><i class="fa-solid fa-circle-check text-yellow text-base mt-0.5 shrink-0"></i><span>' + t + '</span></li>';
    }).join('');
    return '<div class="bg-white rounded-xl shadow-md overflow-hidden border border-gray-100 flex flex-col justify-between"><div><div class="relative h-48 bg-gray-200"><img src="' + c[0] + '" alt="' + c[1] + '" class="w-full h-full object-cover" onerror="this.src=\'' + c[8] + '\'"><div class="absolute top-3 left-3 text-xs font-bold px-3 py-1.5 rounded-full uppercase tracking-wider shadow" style="background:' + c[3] + ';color:' + c[4] + '">' + c[2] + '</div></div><div class="p-5"><h3 class="text-lg font-bold text-gray-900 mb-3">' + c[5] + '</h3><ul class="space-y-2 text-sm text-gray-600 mb-5">' + lis + '</ul></div></div><div class="px-5 pb-5"><a href="#cotizacion" class="inline-flex w-full items-center justify-center gap-2 bg-[#0B1E3D] hover:bg-blue text-white font-semibold py-2.5 rounded-lg transition shadow-sm"><i class="fa-solid fa-cart-shopping text-yellow"></i>' + c[7] + '</a></div></div>';
  }).join('');
  return '<section id="motores" class="bg-paper py-16 sm:py-20"><div class="mx-auto max-w-[90rem] px-4 sm:px-6"><div class="mx-auto mb-4 max-w-3xl text-center"><p class="inline-flex rounded-full bg-yellow/20 px-3 py-1 text-[0.68rem] font-bold uppercase tracking-[0.16em] text-gold">Catálogo de sistemas</p><h2 class="mt-3 font-display text-4xl font-extrabold uppercase tracking-tight text-navy sm:text-5xl">Tenemos todos los sistemas de puertas de garaje</h2><p class="mt-3 text-muted">Te brindamos una atención y asesoría personalizada. Tenemos la puerta que tu proyecto necesita.</p></div><div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">' + items + '</div></div>';
})();
